ExUnit.start()
ExUnit.configure(exclude: [:disabled])
Ecto.Adapters.SQL.Sandbox.mode(App.Repo, :manual)
Test.NuxtHelper.generate_nuxt_client!()
Application.put_env(:wallaby, :base_url, Web.Endpoint.url() <> "/client_test/index.html")
{:ok, _} = Application.ensure_all_started(:wallaby)
