defmodule App.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:user_token, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :token, :binary
      add :context, :text
      add :sent_to, :text

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id, :uuid, null: false
    end

    create table(:user_account, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:user_token) do
      modify :user_id,
             references(:user_account,
               column: :id,
               name: "user_token_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create unique_index(:user_token, [:context, :token], name: "user_token_token_context_index")

    alter table(:user_account) do
      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :username, :citext, null: false
      add :hashed_password, :text
      add :email, :citext, null: false
      add :first_name, :text, null: false
      add :surname, :text, null: false
      add :roles, {:array, :text}, null: false
    end

    create unique_index(:user_account, [:email], name: "user_account_unique_email_index")

    create unique_index(:user_account, [:username], name: "user_account_unique_username_index")
  end

  def down do
    drop_if_exists unique_index(:user_account, [:username],
                     name: "user_account_unique_username_index"
                   )

    drop_if_exists unique_index(:user_account, [:email], name: "user_account_unique_email_index")

    alter table(:user_account) do
      remove :roles
      remove :surname
      remove :first_name
      remove :email
      remove :hashed_password
      remove :username
      remove :updated_at
      remove :created_at
    end

    drop_if_exists unique_index(:user_token, [:context, :token],
                     name: "user_token_token_context_index"
                   )

    drop constraint(:user_token, "user_token_user_id_fkey")

    alter table(:user_token) do
      modify :user_id, :uuid
    end

    drop table(:user_account)

    drop table(:user_token)
  end
end
